version: "3.8"
services:
  database:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_DATABASE=root
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - 5432:5432
      